--[[---------------------------------------DESCRIPTION------------------------------------------
	Plays the Blender-authored launcher clips (SnowballAnimations/LauncherClips/Lnn, generated by
	ras-dev/launcher-anims/tools/to_luau.py). No Animation assets: the samples are written
	straight into the joint Transforms by ChargeController, so they play in any game whoever
	owns it, and every client can run them for every character.

	ClipPlayer.Load(launcherId) -> data or nil (nil = no clips, use the procedural profile)
	ClipPlayer.Sample(data, kind, time, out) -> out[jointName] = CFrame (joint Transform)
	    kind: "Ready" | "ChargeLo" | "ChargeHi" (loops) | "Fire" (clamped)
	ClipPlayer.Frame(data, name, scale) -> CFrame of a Meta point (Muzzle, Seat ...) in the
	    launcher's grip-pivot frame at the given model scale (the data is at template scale)

	Samples are Catmull-Rom interpolated (15 fps loops, 30 fps Fire), quaternions renormalised.

--------------------------------------------------------------------------------------------]]--

local ClipPlayer = {}

local clipsFolder = script.Parent:FindFirstChild("LauncherClips")
local cache = {}

local function prepare(data)
	-- Per-joint offsets into a flat frame: 4 quaternion numbers, +3 translation for Moves joints.
	local moves = {}
	for _, index in ipairs(data.Moves or {}) do
		moves[index] = true
	end
	local offsets, cursor = {}, 1
	for index = 1, #data.Joints do
		offsets[index] = { cursor, moves[index] == true }
		cursor += if moves[index] then 7 else 4
	end
	data._offsets = offsets
	return data
end

function ClipPlayer.Load(launcherId)
	if type(launcherId) ~= "number" then
		return nil
	end
	local cached = cache[launcherId]
	if cached ~= nil then
		return cached or nil
	end
	local module = clipsFolder and clipsFolder:FindFirstChild(string.format("L%02d", launcherId))
	local data = false
	if module and module:IsA("ModuleScript") then
		local ok, result = pcall(require, module)
		if ok and type(result) == "table" and result.Clips and result.Clips.Fire then
			data = prepare(result)
		else
			warn("[CLIENT]: Launcher clip module failed to load:", module:GetFullName(), result)
		end
	end
	cache[launcherId] = data
	return data or nil
end

local function catmull(p0, p1, p2, p3, t, t2, t3)
	return 0.5 * ((2 * p1) + (p2 - p0) * t + (2 * p0 - 5 * p1 + 4 * p2 - p3) * t2 + (3 * p1 - p0 - 3 * p2 + p3) * t3)
end

function ClipPlayer.Sample(data, kind, time, out)
	out = out or {}
	local clip = data.Clips[kind]
	if not clip then
		return out
	end
	local frames = clip.Frames
	local count = #frames
	local f = time * clip.Fps
	local i0, i1, i2, i3, frac
	if clip.Loop and count > 2 then
		local period = count - 1 -- the last frame repeats the first
		f %= period
		local base = math.floor(f)
		frac = f - base
		i1 = base + 1
		i0 = (base - 1) % period + 1
		i2 = (base + 1) % period + 1
		i3 = (base + 2) % period + 1
	else
		f = math.clamp(f, 0, count - 1)
		local base = math.min(math.floor(f), count - 1)
		frac = f - base
		i1 = base + 1
		i0 = math.max(i1 - 1, 1)
		i2 = math.min(i1 + 1, count)
		i3 = math.min(i1 + 2, count)
	end
	local a, b, c, d = frames[i0], frames[i1], frames[i2], frames[i3]
	local t, t2, t3 = frac, frac * frac, frac * frac * frac
	for index, name in ipairs(data.Joints) do
		local offset = data._offsets[index]
		local o = offset[1]
		local bw, bx, by, bz = b[o], b[o + 1], b[o + 2], b[o + 3]
		-- keep the neighbours on the same hemisphere as the current sample
		local aw, ax, ay, az = a[o], a[o + 1], a[o + 2], a[o + 3]
		if aw * bw + ax * bx + ay * by + az * bz < 0 then
			aw, ax, ay, az = -aw, -ax, -ay, -az
		end
		local cw, cx, cy, cz = c[o], c[o + 1], c[o + 2], c[o + 3]
		if cw * bw + cx * bx + cy * by + cz * bz < 0 then
			cw, cx, cy, cz = -cw, -cx, -cy, -cz
		end
		local dw, dx, dy, dz = d[o], d[o + 1], d[o + 2], d[o + 3]
		if dw * cw + dx * cx + dy * cy + dz * cz < 0 then
			dw, dx, dy, dz = -dw, -dx, -dy, -dz
		end
		local qw = catmull(aw, bw, cw, dw, t, t2, t3)
		local qx = catmull(ax, bx, cx, dx, t, t2, t3)
		local qy = catmull(ay, by, cy, dy, t, t2, t3)
		local qz = catmull(az, bz, cz, dz, t, t2, t3)
		local m = math.sqrt(qw * qw + qx * qx + qy * qy + qz * qz)
		if m < 1e-6 then
			qw, qx, qy, qz, m = 1, 0, 0, 0, 1
		end
		local px, py, pz = 0, 0, 0
		if offset[2] then
			local p = o + 4
			px = catmull(a[p], b[p], c[p], d[p], t, t2, t3)
			py = catmull(a[p + 1], b[p + 1], c[p + 1], d[p + 1], t, t2, t3)
			pz = catmull(a[p + 2], b[p + 2], c[p + 2], d[p + 2], t, t2, t3)
		end
		out[name] = CFrame.new(px, py, pz, qx / m, qy / m, qz / m, qw / m)
	end
	return out
end

-- A per-frame number track of a clip (e.g. Tip = the launcher tip's height above the floor on
-- the authoring rig), linearly interpolated at `time`; nil when the clip has no such track.
function ClipPlayer.Track(data, kind, name, time)
	local clip = data.Clips[kind]
	local track = clip and clip[name]
	if not track then
		return nil
	end
	local count = #track
	local f = time * clip.Fps
	if clip.Loop and count > 2 then
		f %= (count - 1)
	else
		f = math.clamp(f, 0, count - 1)
	end
	local i = math.floor(f)
	local a = track[i + 1]
	local b = track[math.min(i + 2, count)]
	return a + (b - a) * (f - i)
end

function ClipPlayer.Length(data, kind)
	local clip = data.Clips[kind]
	return clip and clip.Length or 0
end

-- Meta point -> CFrame in the grip-pivot frame at `scale` (1 = template, LAUNCHER.Scale in game).
function ClipPlayer.Frame(data, name, scale)
	local entry = data.Meta and data.Meta[name]
	if not entry then
		return nil
	end
	local pos = entry.Pos * (scale or 1)
	local look = entry.Look or Vector3.new(0, -1, 0)
	local up = entry.Up or Vector3.new(0, 0, -1)
	return CFrame.lookAt(pos, pos + look, up)
end

return ClipPlayer
