"""out/NN.json (launcherlib.export) -> Luau clip module(s) for ReplicatedStorage.Assets.SnowballAnimations.Clips

    python tools/to_luau.py <out_dir_with_json> <dest_dir>      (writes L01.luau ... for every NN.json)

Module shape (read by SnowballAnimations/ClipPlayer):
    return {
        Id, Name, FireAt, Ball = {Show, Start, Grow, Scale}, Kind,
        Joints = {"LowerTorso", ..., "Launcher"},    -- joint order of every frame
        Moves = {1},                                 -- joints that also carry a translation (studs)
        Meta = {Muzzle = {Pos, Look, Up}, Seat = ..., Grip2 = ..., Bands = {...}},  -- pivot frame, template scale
        Clips = {Ready = {Length, Fps, Loop, Frames = {{qw,qx,qy,qz, ... [px,py,pz for Moves joints]}, ...}}, ...},
    }
Loops (Ready / ChargeLo / ChargeHi) are resampled to 15 fps, Fire keeps 30 fps.  Quaternions are
made sign-continuous so the runtime's Catmull-Rom never swings the long way round.
"""
import json
import math
import os
import sys

LOOP_FPS = 15
FIRE_FPS = 30
LOOPS = ("Ready", "ChargeLo", "ChargeHi")


def fmt(x, k=3):
    s = ("%." + str(k) + "f") % x
    s = s.rstrip("0").rstrip(".") if "." in s else s
    if s in ("-0", ""):
        s = "0"
    return s


def v3(v):
    return "Vector3.new(%s, %s, %s)" % (fmt(v[0], 4), fmt(v[1], 4), fmt(v[2], 4))


def meta_lua(meta):
    out = []
    for key, e in meta.items():
        if key in ("Name",):
            continue
        if key == "Kind":
            out.append('\t\tKind = "%s",' % e)
        elif key == "Bands":
            out.append("\t\tBands = {%s}," % ", ".join(v3(b) for b in e))
        elif isinstance(e, dict):
            parts = ["Pos = " + v3(e["pos"])]
            if "look" in e:
                parts.append("Look = " + v3(e["look"]))
            if "up" in e:
                parts.append("Up = " + v3(e["up"]))
            out.append("\t\t%s = {%s}," % (key, ", ".join(parts)))
        elif isinstance(e, list):
            out.append("\t\t%s = {Pos = %s}," % (key, v3(e)))
    return out


def resample(frames, src_fps, dst_fps, length):
    if src_fps == dst_fps:
        return frames
    n = int(round(length * dst_fps))
    res = []
    for i in range(n + 1):
        t = i / dst_fps * src_fps
        a = min(int(math.floor(t)), len(frames) - 1)
        b = min(a + 1, len(frames) - 1)
        f = t - a
        row = []
        for ja, jb in zip(frames[a], frames[b]):
            qa, qb = ja[:4], jb[:4]
            if sum(x * y for x, y in zip(qa, qb)) < 0:
                qb = [-x for x in qb]
            q = [x + (y - x) * f for x, y in zip(qa, qb)]
            m = math.sqrt(sum(x * x for x in q)) or 1.0
            q = [x / m for x in q]
            p = [x + (y - x) * f for x, y in zip(ja[4:], jb[4:])]
            row.append(q + p)
        res.append(row)
    return res


def convert(src, dest_dir):
    with open(src) as fh:
        data = json.load(fh)
    lid = data["id"]
    bones = data["bones"]
    spec = data["spec"]
    clips = data["clips"]
    # joints that ever translate
    moves = []
    for j in range(len(bones)):
        if any(abs(c) > 1e-3 for clip in clips.values() for fr in clip["frames"] for c in fr[j][4:7]):
            moves.append(j)
    lines = [
        "--[[",
        "\tGENERATED by ras-dev/launcher-anims/tools/to_luau.py from the Blender clip export",
        "\tout/%02d.json (launchers/%02d/build.py).  Do not edit by hand: change the build script," % (lid, lid),
        "\tre-run it in Blender and regenerate.  Read by SnowballAnimations/ClipPlayer.",
        "]]",
        "return {",
        "\tId = %d," % lid,
        '\tName = "%s",' % data["name"],
        "\tFireAt = %s," % fmt(spec.get("FireAt", 0.3), 3),
    ]
    ball = spec.get("Ball", {})
    if spec.get("BallAppearAt") is not None:
        lines.append("\tBallAppearAt = %s," % fmt(spec["BallAppearAt"], 3))
    extra = ""
    if ball.get("hand"):
        extra += ', Hand = "%s"' % ball["hand"]
    if ball.get("offset"):
        extra += ", Offset = " + v3(ball["offset"])
    lines.append('\tBall = {Show = "%s", Start = "%s", Grow = %s, Scale = %s%s},' % (
        ball.get("show", "Never"), ball.get("start", "Muzzle"), fmt(ball.get("grow", 1.0)), fmt(ball.get("scale", 1.0)), extra))
    if spec.get("Fx"):
        fx = spec["Fx"]
        parts = []
        for k, v in fx.items():
            if v is None:
                continue
            if isinstance(v, str):
                parts.append('%s = "%s"' % (k, v))
            elif isinstance(v, (list, tuple)) and len(v) == 3:
                # colours come as 0-255 or, from some scripts, as 0-1 fractions
                c = [x * 255.0 for x in v] if max(v) <= 1.0 else list(v)
                parts.append("%s = Color3.fromRGB(%d, %d, %d)" % (k, round(c[0]), round(c[1]), round(c[2])))
            else:
                parts.append("%s = %s" % (k, fmt(v)))
        lines.append("\tFx = {%s}," % ", ".join(parts))
    lines.append("\tJoints = {%s}," % ", ".join('"%s"' % b for b in bones))
    lines.append("\tMoves = {%s}," % ", ".join(str(j + 1) for j in moves))
    lines.append("\tMeta = {")
    lines.extend(meta_lua(data.get("meta", {})))
    lines.append("\t},")
    lines.append("\tClips = {")
    for kind in ("Ready", "ChargeLo", "ChargeHi", "Fire"):
        if kind not in clips:
            continue
        clip = clips[kind]
        length = clip["length"]
        loop = kind in LOOPS
        fps = LOOP_FPS if loop else FIRE_FPS
        frames = resample(clip["frames"], data["fps"], fps, length)
        # sign continuity
        prev = None
        for row in frames:
            if prev is not None:
                for j in range(len(row)):
                    if sum(a * b for a, b in zip(row[j][:4], prev[j][:4])) < 0:
                        row[j][:4] = [-x for x in row[j][:4]]
            prev = row
        tip_lua = ""
        if clip.get("tip"):
            # expected tip height above the floor per frame (floor-contact launchers)
            step = int(round(data["fps"] / fps))
            tip_lua = " Tip = {%s}," % ",".join(fmt(x, 2) for x in clip["tip"][::step])
        lines.append("\t\t%s = {Length = %s, Fps = %d, Loop = %s,%s Frames = {" % (kind, fmt(length), fps, "true" if loop else "false", tip_lua))
        for row in frames:
            nums = []
            for j, e in enumerate(row):
                nums.extend(fmt(x, 3) for x in e[:4])
                if j in moves:
                    nums.extend(fmt(x, 3) for x in e[4:7])
            lines.append("\t\t\t{%s}," % ",".join(nums))
        lines.append("\t\t}},")
    lines.append("\t},")
    lines.append("}")
    os.makedirs(dest_dir, exist_ok=True)
    dest = os.path.join(dest_dir, "L%02d.luau" % lid)
    with open(dest, "w", newline="\n") as fh:
        fh.write("\n".join(lines) + "\n")
    return dest, os.path.getsize(dest)


if __name__ == "__main__":
    src_dir, dest_dir = sys.argv[1], sys.argv[2]
    only = set(sys.argv[3:])
    for fn in sorted(os.listdir(src_dir)):
        if fn.endswith(".json") and fn[:2].isdigit():
            if only and fn[:2] not in only:
                continue
            d, size = convert(os.path.join(src_dir, fn), dest_dir)
            print("wrote", d, size, "bytes")
